services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - estudo   
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    ports:
      - ${PGADMIN_PORT:-5050}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin  
    networks:
      - estudo     
    depends_on:
      - db  
volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local  
networks:
  estudo:
    driver: bridge